### ISSUE TITLE
VPN Addition for the possibility of JIT without being next to a computer

### ISSUE THREAD

**Issue by Montivillon** [nythepegasus/SideJITServer#10]
Right now, SideJITServer only works when your beside or next to your computer, but if I suggested that SideJITServer will have VPN, it could work and allows it that you don’t have to be beside your computer but still needed the program to be installed to the computer. This is just a recommendation and at least just try

**Comment by WesleyBryie** [comment]
SideJITServer is currently not, and will likely never work with VPNs.

1. The current setup involves using the TUN driver which breaks most VPN connections.
2. Most VPNs don't support mDNS/Bonjour (required for device discovery) because Apple devices don't announce mDNS/Bonjour over VPN connections.

Wesley Bryie

***@***.***
***@***.***

https://wesbryie.com/
________________________________
From: Montivillon ***@***.***>
Sent: Thursday, April 11, 2024 12:51:38 AM
To: nythepegasus/SideJITServer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nythepegasus/SideJITServer] VPN Addition for the possibility of JIT without being next to a computer (Issue #10)


Right now, SideJITServer only works when your beside or next to your computer, but if I suggested that SideJITServer will have VPN, it could work and allows it that you don’t have to be beside your computer but still needed the program to be installed to the computer. This is just a recommendation and at least just try
