### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by MRAnone1** [nythepegasus/SideJITServer#101]
I tried to run the Server, but it would always get stuck at `Uvicorn running on http://127.0.0.1:49151` After that It errors with the error: `/Users/myuser/venv./lib/python3.12/site-packages/pymobiledevice3/utils.py:55: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()` I'm using an M1 MBP 2021

**Comment by GanjaLoop** [comment]
Try it      pip install --upgrade pymobiledevice3
Or if u using asyncio.getrunningloop() try using asyncio.geteventloop() instead

**Comment by CodexHub58** [comment]
1.Suppress the deprecation warning: You can suppress the deprecation warning by adding the following code at the beginning of your script:
**Copy code**
```
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
```
2.Update pymobiledevice3: The deprecation warning is likely due to the library using an outdated method to get the event loop. You can try updating pymobiledevice3 to the latest version using pip:

**Copy code**
`pip install --upgrade pymobiledevice3`
If an update is available, this might resolve the issue.

3.Use the asyncio.run() function: Instead of using asyncio.get_event_loop(), you can use the asyncio.run() function, which is the recommended way to run asynchronous code in Python 3.7 and later. However, this might require changes to your code and dependencies.

4.Check for compatibility issues with M1 MBP 2021: As you're using an M1 MBP 2021, there might be compatibility issues with certain libraries or dependencies. You can try running your application on a different machine or in a virtual environment to isolate the issue.

5.Check for conflicts with other libraries: If you're using other libraries that also use asyncio, there might be conflicts. Try uninstalling and reinstalling the conflicting libraries.

**Comment by nythepegasus** [comment]
Could you try the latest update? I think I fixed the runningloop errors, but I could be wrong.
