### ISSUE TITLE
Question: Is there support for vpn networks such as Tailscale?

### ISSUE THREAD

**Issue by AttakDoge** [nythepegasus/SideJITServer#94]
I don’t always have my computer with me (desktop pc) so I was wondering if vpns such as Tailscale would work with this.

**Comment by fish4terrisa-MSDSM** [comment]
And I also want to ask. Also, SideJITServer seems only working when the devices is paired with the usbmuxd on the computer.... So we also need to get the netmuxd working through tailscale...

**Comment by fish4terrisa-MSDSM** [comment]
If we can connect the devices with netmuxd through tailscale, it will work(I think). (In my situation, I'm trying to get SideJITServer running on my vps, so I also have to use USB/IP to make my vps connect to my devices once at first)

**Comment by nythepegasus** [comment]
As far as I know this is not feasible. If anyone writes a guide on how to do it, I will change my mind but for now that isn't this project's focus.

**Comment by fish4terrisa-MSDSM** [comment]
> As far as I know this is not feasible. If anyone writes a guide on how to do it, I will change my mind but for now that isn't this project's focus.

I tried to connect my ipad through tailscale... And it seems half succeed:
I edit the avahi config on my VPS to force it to detect the ipad through the VPN...and the usbmuxd really connected my device(currently i'm using usbmuxd2).
The ideviceinfo and may other idevice tools worked well, as the ideviceinfo can give the correct info after connected, and can get the new device name when I changed the device name after pairing...so it seems that the usbmuxd2 can get new information from my device through VPN.(However, after a few minute, usually 5 to 10 minutes, it'll have heartbeat issues...Maybe that's because the avahi records are gone)
But SideJITServer currently doesn't works well with usbmuxd2(usbmuxd2 doesn't support pymobiledevice3), so I've never got any success with SideJITServer in this way. :-(
